server:
  port: 80

# 数据源配置
spring:
  redis:
    host: 118.24.127.192
    port: 6379
    password: 123456
    database: 1
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://locahost:3306/test?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver